output = "D:/g/git/ippras-blcs/storage"

[temperature]
address = "192.168.0.113:5502"
count = 3
finish = 10
flush = 60
interval = 1

[turbidity]
address = "192.168.0.148:5502"
count = 1
finish = 10
flush = 60
interval = 1
